#pragma config(Sensor, S1,     ll,             sensorAnalogActive)
#pragma config(Sensor, S2,     mm,             sensorAnalogActive)
#pragma config(Sensor, S3,     rr,             sensorAnalogActive)
#pragma config(Sensor, S4,     ARDUINO,            sensorI2CCustom)
#pragma config(Motor,  motorA,          l,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          r,             tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "dInclude.h"

task main()
{
	clearDebugStream();
	bool lastCornerVal[4];
	ClearTimer(T1);
	StartTask(Ard);
	delay(500); //let sensor init
	while(true)
	{
		Light[left] = SensorValue(ll);
    Light[mid] = SensorValue(mm);
    Light[right] = SensorValue(rr);
		if((Light[left] < CalLeft) && (Light[mid] < CalMid) && (Light[right] > CalRight))
		{
			//writeDebugStream("Left:\t");
			nxtDisplayCenteredBigTextLine(1,"Left");
			//while((Light[left] < CalLeft)) {Light[left] = SensorValue(ll); writeDebugStreamLine("In While"); }
			lastCornerVal[0]=(Light[left] < CalLeft);
			lastCornerVal[1]=(Light[mid] < CalMid);
			lastCornerVal[2]=(Light[right] < CalRight);
			ClearTimer(T1);
			delay(25);
			FastLeft();
			delay(100);
		}
		Light[left] = SensorValue(ll);
    Light[mid] = SensorValue(mm);
    Light[right] = SensorValue(rr);
		if((Light[mid] < CalMid))
		{
			//writeDebugStream("Straight:\t");
			nxtDisplayCenteredBigTextLine(1,"Straight");
			Drive();
			delay(10);
		}
		Light[left] = SensorValue(ll);
    Light[mid] = SensorValue(mm);
    Light[right] = SensorValue(rr);
		if((Light[left] > CalLeft) && (Light[mid] < CalMid) && (Light[right] < CalRight))
		{
			//writeDebugStream("Right:\t");
			nxtDisplayCenteredBigTextLine(1,"Right");
			//while((Light[right] < CalRight)) {Light[right] = SensorValue(rr); writeDebugStreamLine("In While"); }
			lastCornerVal[0]=(Light[left] < CalLeft);
			lastCornerVal[1]=(Light[mid] < CalMid);
			lastCornerVal[2]=(Light[right] < CalRight);
			ClearTimer(T1);
			delay(25);
			FastRight();
			delay(100);
		}
		Light[left] = SensorValue(ll);
    Light[mid] = SensorValue(mm);
    Light[right] = SensorValue(rr);
		if((Light[mid] < CalMid))
		{
			//writeDebugStream("Straight:\t");
			nxtDisplayCenteredBigTextLine(1,"Straight");
			Drive();
			delay(10);
		}
		if((Light[left]<CalLeft)&&(Light[mid]<CalMid)&&(Light[right]<CalRight))
		{
			if(time1[T1]<1000 && lastCornerVal[0] == false && lastCornerVal[1] == true && lastCornerVal[2] == true)
			{
				nxtDisplayCenteredBigTextLine(5,"GreenRight");
				delay(20);
				FastRight();
				while(SensorValue(mm) > CalMid) { }
				Drive();
			}
			if(time1[T1]<1000 && lastCornerVal[0] == true && lastCornerVal[1] == true && lastCornerVal[2] == false)
			{
				nxtDisplayCenteredBigTextLine(5,"GreenLeft");
				delay(20);
				FastLeft();
				while(SensorValue(mm) > CalMid) { }
				Drive();
			}
		}
		nxtDisplayCenteredTextLine(3,"%d|%d|%d",lastCornerVal[0],lastCornerVal[1],lastCornerVal[2]);
		nxtDisplayCenteredTextLine(4,"%d",time1[T1]);
		//writeDebugStreamLine("%d | %d | %d", Light[left], Light[mid], Light[right]);
		//delay(10);
	}
}
