#pragma config(Motor,  motorA,          l,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          r,             tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma DebuggerWindows("joystickSimple");

#include "JoystickDriver.c"

int LeftM, RightM, Both, Xmap, Ymap, rawY;

task main()
{
	while(true)
	{
		getJoystickSettings(joystick);
		Xmap = joystick.joy1_x1 / 2;
		Ymap = joystick.joy1_y1 / 1.5;
		if(Xmap >= -6 && Xmap <= 6)
			Xmap = 0;
		if(Ymap >= -6 && Ymap <= 6)
			Ymap = 0;
		Both = Ymap;
		if(Xmap < 0)
		{
			LeftM = Both - abs(Xmap);
			RightM = Both + abs(Xmap);
		}
		if(Xmap >= 0)
		{
			LeftM = Both + abs(Xmap);
			RightM = Both - abs(Xmap);
		}
		motor[l] = LeftM;
		motor[r] = RightM;
	}
}
