#pragma config(Sensor, S1,     ST,             sensorTouch)
#pragma config(Motor,  motorB,          ML,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          MR,            tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true)
{
if(SensorValue[S1] == 1)
{
	motor[motorB] = 30;
  motor[motorC] = 30;
}
else
	motor[motorB] = 0;
  motor[motorC] = 0;

}
}
