#pragma config(Sensor, S2,     HTSMUX,              sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * $Id: hitechnic-colour-v1-SMUX-test1.c 133 2013-03-10 15:15:38Z xander $
 */

/**
 * hitechnic-colour-v1.h provides an API for the HiTechnic Color Sensor.  This program
 * demonstrates how to use that API.
 *
 * Changelog:
 * - 0.1: Initial release
 * - 0.2: More comments
 * - 0.3: Now uses HTSMUX driver which has been split from common.h\n
 *        HTSMUX initialisation and scanning functions have been removed\n
 *
 * Credits:
 * - Big thanks to HiTechnic for providing me with the hardware necessary to write and test this.
 *
 * License: You may use this code as you wish, provided you give credit where it's due.
 *
 * THIS CODE WILL ONLY WORK WITH ROBOTC VERSION 3.59 AND HIGHER.

 * Xander Soldaat (xander_at_botbench.com)
 * 20 February 2011
 * version 0.3
 */

#include "drivers/hitechnic-sensormux.h"
#include "drivers/hitechnic-colour-v1.h"
#include "drivers/lego-light.h"

// The sensor is connected to the first port
// of the SMUX which is connected to the NXT port S1.
// To access that sensor, we must use msensor_S1_1.  If the sensor
// were connected to 3rd port of the SMUX connected to the NXT port S4,
// we would use msensor_S4_3

// Give the sensor a nice easy to use name
const tMUXSensor LDR = msensor_S2_1;
const tMUXSensor HTCOLOR2 = msensor_S2_2;
const tMUXSensor HTCOLOR3 = msensor_S2_3;

task main () {
  int color2 = 0;
  int red2 = 0;
  int green2 = 0;
  int blue2 = 0;

  int color3 = 0;
  int red3 = 0;
  int green3 = 0;
  int blue3 = 0;

  int light = 0;

  int Timer1, Timer2, Timer3 = 0;

  eraseDisplay();
  while (true) {

    ClearTimer(T1);

    // Read the currently detected colour from the sensor
    color2 = HTCSreadColor(HTCOLOR2);
    HTCSreadRGB(HTCOLOR2, red2, green2, blue2);
    Timer1 = time1[T1];


    ClearTimer(T1);

    color3 = HTCSreadColor(HTCOLOR3);
    HTCSreadRGB(HTCOLOR3, red3, green3, blue3);
    Timer2 = time1[T1];

    ClearTimer(T1);

    light = LSvalRaw(LDR);
    Timer3 = time1[T1];


    // Read the RGB values of the currently colour from the sensor
    // A return value of false implies an error has occurred
    nxtDisplayCenteredTextLine(0, "Color2: %2d", color2);
    nxtDisplayCenteredTextLine(1, "Color3: %2d", color3);
    nxtDisplayCenteredTextLine(2, "R  G  B");
    nxtDisplayCenteredTextLine(3, "%3d %3d %3d", red2, green2, blue2);
    nxtDisplayCenteredTextLine(4, "%3d %3d %3d", red3, green3, blue3);

    nxtDisplayCenteredTextLine(6, "%d", light);
    nxtDisplayCenteredTextLine(7, "%d, %d, %d", Timer1, Timer2, Timer3);

    wait1Msec(100);
  }
}

/*
 * $Id: hitechnic-colour-v1-SMUX-test1.c 133 2013-03-10 15:15:38Z xander $
 */
