#pragma config(Sensor, S1,     HTCSL,          sensorI2CCustom)//links
#pragma config(Sensor, S2,     Sl,             sensorLightActive)//mitte
#pragma config(Sensor, S3,     HTCSR,          sensorI2CCustom)//rechts
#pragma config(Sensor, S4,     mux,            sensorI2CCustom)
#pragma config(Motor,  motorA,          Mg,            tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          MR,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          ML,            tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "dInclude.h"

int _x_axis, _y_axis, _z_axis = 0;

const tMUXSensor port1 = msensor_S4_1;
const tMUXSensor port2 = msensor_S4_2;
const tMUXSensor port3 = msensor_S4_3;
const tMUXSensor port4 = msensor_S4_4;

void delay(int msec)
{
	wait1Msec(msec);
}

task main()
{

	motor[motorB] = 25;
	motor[motorC] = 25;

	delay(1500);

	motor[motorB] = 0;
	motor[motorC] = 0;

	delay(500);

	motor[motorB] = -25;
	motor[motorC] = -25;

	delay(1500);

	motor[motorB] = 0;
	motor[motorC] = 0;

	if(HTCSreadColor(HTCSL))
	{
		PlaySound(soundBeepBeep);
		nxtDisplayCenteredTextLine(0,"Left, ERROR");
	}
	else
		nxtDisplayCenteredTextLine(0,"Left, NO error");

	if(HTCSreadColor(HTCSR))
	{
		PlaySound(soundBeepBeep);
		nxtDisplayCenteredTextLine(1,"Right, ERROR");
	}
	else
		nxtDisplayCenteredTextLine(1,"Right, NO error");

	if(sensorvalue[S2] == 0)
	{
		PlaySound(soundBeepBeep);
		nxtDisplayCenteredTextLine(2,"Midd, ERROR");
	}
	else
		nxtDisplayCenteredTextLine(2,"Midd, NO error");

HTACreadAllAxes(port4, _x_axis, _y_axis, _z_axis);
if(_x_axis == 0)
{
PlaySound(soundBeepBeep);
nxtDisplayCenteredTextLine(3,"accel, ERROR");
}
else
nxtDisplayCenteredTextLine(3,"accel, NO error");



	while(true){}
}
