#pragma config(Sensor, S1,     s,              sensorAnalogInactive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/common.h"
#include "drivers/hitechnic-colour-v1.h"

int red = 0;
int green = 0;
int blue = 0;
int _color = 0;
int ldr = 0;

task main()
{
	while(true)
	{
		ClearTimer(T1);
		SetSensorType(s, sensorI2CCustom);
		nxtDisplayCenteredTextLine(0, "%d", time1[T1]);
		_color = HTCSreadColor(s);
		HTCSreadRGB(s, red, green, blue);
		SetSensorType(s, sensorLightActive);
		ldr = SensorValue(s);
		nxtDisplayCenteredTextLine(2, "%1d", _color);
		nxtDisplayCenteredTextLine(4, "%2d, %2d, %2d", red, green, blue);
		nxtDisplayCenteredTextLine(6, "%3d", ldr);
		wait1Msec(10);
	}
}
