#pragma config(Sensor, S1,     Mux,            sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-sensormux.h"
#include "drivers/lego-light.h"

const tMUXSensor port1 = msensor_S1_1;
const tMUXSensor port2 = msensor_S1_2;
const tMUXSensor port3 = msensor_S1_3;
const tMUXSensor port4 = msensor_S1_4;

task main()
{
	while(true)
	{
		nxtDisplayCenteredTextLine(1, "raw,norm");
		nxtDisplayCenteredTextLine(2, "1: %d | %d", LSvalRaw(port1), LSvalNorm(port1));
		nxtDisplayCenteredTextLine(3, "2: %d | %d", LSvalRaw(port2), LSvalNorm(port2));
		if(LSvalNorm(port1) > 45)
			nxtDisplayCenteredTextLine(4, "1:schwarz");
		else
			nxtDisplayCenteredTextLine(4, "1:weiss");

		if(LSvalNorm(port2) > 43)
			nxtDisplayCenteredTextLine(5, "2:schwarz");
		else
			nxtDisplayCenteredTextLine(5, "2:weiss");
	}
}
