#pragma config(Sensor, S1,     links,          sensorTouch)
#pragma config(Sensor, S2,     rechts,         sensorTouch)
#pragma config(Sensor, S3,     mains,          sensorLightActive)
#pragma config(Motor,  motorA,          Links,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          Greifarm,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          Rechts,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true)
{
	if(sensorValue[S1] == 1)
	{
		motor[motorB] = 30;
	}
	if(sensorValue[S1] == 0)
	{
		motor[motorB] = 0;
	}
	if(sensorValue[S1] == 1 && SensorValue[S2] == 1)
	{
		motor[motorA] = 25;
		motor[motorC] = 25;

	}
	else if
	{
		motor[motorA] = 0;
		motor[motorC] = 5;
	}
	if(SensorValue[mains] >= 30 && SensorValue[mains] <= 40)
	{
		nxtDisplayCenteredTextLine(4,"white");
	}
}
}
